StockHaus.UI/Areas/Admin/Controllers/TraceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StockHaus.Core.BaseService;
using PagedList;
using PagedList.Mvc;
using StockHaus.ModelClass.AdminPage;
using StockHaus.ModelClass.AreaController;
using StockHaus.ModelClass.UserPage;

namespace StockHaus.UI.Areas.Admin.Controllers
{
    public class TraceController : Controller
    {
        ServicePoints point;
        public TraceController()
        {
            point = new ServicePoints();
        }
        //
        // GET: /Admin/Trace/

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public PartialViewResult InventoryLog(string id)
        {
            int idx = int.Parse(id);

            var _matlist = point.InventoryService.InvToList();

            if (_matlist.Count < 51)
            {
                if (_matlist.Count == 0)
                {
                    return null;
                }
                // 21 den az ise belge sayısı olduğu kadar ı gösterilecek 9 sa 9 u gibi
                var _list = _matlist.OrderByDescending(x => x.ID).ToPagedList(idx, _matlist.Count);
                return PartialView("_PartialLogMaterial", _list);
            }
            // birinci sayfa açılsın,20 tane göstersin anlamında
            var _list2 = _matlist.OrderByDescending(x => x.ID).ToPagedList(idx, 50);

            return PartialView("_PartialLogMaterial", _list2);
        }

        [HttpPost]
        public PartialViewResult TraceStockCount()
        {
            // her bir depo ve stok yeri içinde sayılmış malzemelerin toplam malzemelere olan oranı belirlenir.
            IList<ShowPercent> sper = new List<ShowPercent>();

            var _cList = point.InventoryService.CountedWareStockPlace();

            // _cList depo ve stok yerlerinden oluşmalı
            foreach (var item in _cList)
            {

                int _countedMaterialX = point.InventoryService.CountedMaterial(item._ware, item._stock);
                int _totalMaterialX = point.MaterialService.GetTotalAmount(item._ware, item._stock);
                int _countApprovedX = point.InventoryService.CountedApproved(item._ware, item._stock);


                double _counted = Convert.ToDouble(_countedMaterialX) / Convert.ToDouble(_totalMaterialX);
                double _appreoved = Convert.ToDouble(_countApprovedX) / Convert.ToDouble(_totalMaterialX);

                ShowPercent spp = new ShowPercent
                {
                    WareHouse = item._ware,
                    StockPlace = item._stock,
                    InventPercent = _counted,
                    ApprovedPercent = _appreoved
                };
                sper.Add(spp);
            }

            return PartialView("_PartialCompletePercent", sper);
        }

        [HttpGet]
        public PartialViewResult InventApprovedMat(int id)
        {
            string _sessionEmail = Session["Email"].ToString();

            var _list = point.InventoryService.ApprovedMaterials();//.GetListMaterial(_sessionEmail, model._matCode, model._matSection, model._matSectionPlace, model._IsInclude);

            if (_list.Count < 51)
            {
                if (_list.Count == 0)
                {
                    return null;
                }
                // 21 den az ise belge sayısı olduğu kadar ı gösterilecek 9 sa 9 u gibi
                var _listX = _list.OrderByDescending(x => x.ID).ToPagedList(id, _list.Count);
                return PartialView("_PartialAppRsltShow", _listX);
            }
            // birinci sayfa açılsın,50 tane göstersin anlamında
            var _list2 = _list.OrderByDescending(x => x.ID).ToPagedList(id, 50);

            return PartialView("_PartialAppRsltShow", _list2);
        }

        [HttpPost]
        public JsonResult ApproveInventMaterial(MissionAssign model)
        {
            // malzeme kodu indisi seri no su ve sayım tablosundaki ID bilgisi alınmalı
            // alınan ID bilgisi İLE takım no suna ulaşılır,buna göre onaylananın ISAPPROVED u 1 olacak,
            // onaylanmayan malzemelerin isactive durumu ise 0 olacak

            foreach (var itemx in model._matList)
            {

                // onaylanacak olan malzemenin invent id si
                var _matContent = point.InventoryService.GetMaterial(itemx._inventId);
                int _ms = 0;

                foreach (var item in _matContent)
                {
                    List<string> _invCodeList = point.InventoryService.FindInventCode(item.MatCode, item.MatIndex, item.MatSpecialStock, item.MatSerialNumber, item.MatSection, item.MatSectionPlace);

                    foreach (var c in _invCodeList)
                    {
                        string[] _data = c.Split('#');
                        int _DataID = int.Parse(_data[0]);
                        string _InventCode = _data[1];

                        InventoriesModel invt = new InventoriesModel
                        {
                            ID = _DataID,
                            ApprovedPers = Session["Email"].ToString(),
                            ApprovedDate = DateTime.Now,
                            IsApproved = true
                        };

                        if (item.ID == _DataID)
                        {
                            // onaylanacak olan malzemenin id si sayım listesinden gelen malzemenin idsine eşitse burada isapprove 1 yapılır
                            _ms = point.InventoryService.UpdateMaterial(invt);
                            if (_ms != 1)
                            {
                                return Json("false");
                            }
                        }
                        else
                        {
                            // onaylanacak olan malzemenin id si sayım listesinden gelen malzemenin idsine eşitse burada isactive 0 yapılır
                            _ms = point.InventoryService.UpdateIsActiveStatus(invt);
                            if (_ms != 1)
                            {
                                return Json("false");
                            }
                        }

                    }

                }
            }

            return Json("true");
        }


        // 3.takımı görevlendir ve material tablosuunda bu verilerin IsCount UNU 1 yap
        [HttpPost]
        public JsonResult AssignAndPassiveMaterial(MissionAssign model)
        {
            string _depo = model._ware;
            string _stokyeri = model._stockPlace;

            //int storeId = point.StoreService.GetStoreID(_depo, _stokyeri);

            // o store id de görevli olan personellerin bilgisi
            //var _biggerStoreId = point.InventoryGroupService.


            // material tablosunda iscount ların 1 yapılması
            foreach (var item in model._matList)
            {
                string _sr = "";
                if (item._serNo == null)
                {
                    _sr = "";
                }
                else
                {
                    _sr = item._serNo;
                }
                MaterialsModel _m = new MaterialsModel
                {
                    MatCode = item._matCode,
                    MatIndex = item._matIndis,
                    MatSerialNumber = _sr,
                    MatSection = model._ware,
                    MatSectionPlace = model._stockPlace
                };
                string _msg = point.MaterialService.UpdateIsCount(_m);
                if (_msg != "true")
                {
                    return Json("false");
                }
            }

            return Json("success");
        }

        [HttpPost]
        public ActionResult GetListMaterial(WareStock model)
        {
            var _matList = point.InventoryService.GetMaterialList(model._ware, model._stock,model._endStockPlace); //.GetMatList(model._ware, model._stock);

            // birinci sayfa açılsın,12 tane göstersin anlamında
            var _list2 = _matList.OrderByDescending(x => x.MatSection).ThenByDescending(c => c.MatSectionPlace).ThenByDescending(v => v.MatCode).ThenByDescending(b => b.MatIndex).ToList();//.ToPagedList(1, 30);

            return PartialView("_PartialListMaterial", _list2);
        }

     

        [HttpPost]
        public JsonResult calcInventMaterial()
        {
            string result = "";

            int _penCount = point.InventoryService.calcPenCount();
            double _totalMatCount = point.InventoryService.calcTotalMatCount();

            result = _penCount + "#" + _totalMatCount;

            return Json(result);
        }

        // depo yeri seçildikten sonra stok yerini doldurur
        [HttpPost]
        public JsonResult SelectStockPlace(string id)
        {
            var _stockPlaceList = point.StoreService.SelectStockPlace(id);

            return Json(_stockPlaceList);
        }

        [HttpGet]
        public ActionResult OpenAppPage(int id)
        {
            SetStockStoreForTrace();
            SetStockPlaceForTrace();
            return PartialView("_PartialChooseWarehouse");
        }

        private void SetStockStoreForTrace(object storeNo = null)
        {
            var _stockStoreList = point.StoreService.SelectStockStoreNo();
            var _selectList = new SelectList(_stockStoreList, storeNo);

            ViewData.Add("_ware", _selectList);
        }

        private void SetStockPlaceForTrace(object placesNo = null)
        {
            var _stockPlaceList = point.StoreService.SelectStockPlaceNo();
            var _selectList = new SelectList(_stockPlaceList, placesNo);
            ViewData.Add("_stock", _selectList);
            ViewData.Add("_endStockPlace", _selectList);
        }
    }
}

StockHaus.UI/Areas/Admin/Views/Shared/_LayoutAdd.cshtml
@using System.Web.Optimization

<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewBag.Title</title>
    <link rel="shortcut icon" href="/logo.ico" />

    <!-- CSS -->
    @*<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:400,100,300,500">*@

    <!-- User Defined CSS -->
    @Styles.Render("~/Areas/Admin/Content/css")
    @Styles.Render("~/Content/themes/base/css")

    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Areas/Admin/Scripts/Add_Site.js"></script>
    <script src="~/Scripts/Sweet/sweetalert-dev.js"></script>
    <link href="~/Content/sweetalert.css" rel="stylesheet" />

</head>
<body>
            <nav id="main" class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu1">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <div id="item-header">
                            <a class="navbar-brand" href="/Admin/Trace">
                                <img class="img-responsive" src="~/Img/logoP.png" />
                            </a>
                        </div>
                    </div>
                    <div class="collapse navbar-collapse" id="menu1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="dropdown">
                                <a id="user" href="#" class="dropdown-toggle" data-toggle="dropdown" style="margin-top:4px;">
                                    <span style="font-weight:bold;font-size:16px;font-family:'Myriad Pro';" id="userNamedTrace">@Session["Email"].ToString()</span>  @*HttpContext.Current.User.Identity.Name*@
                                    <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu dm_Menu">
                                    <li>
                                        <a href="~/Admin/Panel/SignOut"><i class="fa fa-fw fa-power-off"></i> Çıkış Yap</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
   
    <div class="container-fluid">
        <!-- default-->
        <div class="row" style="margin-top:5px;">
            @RenderBody()
        </div>
    </div>
</body>
</html>

StockHaus.UI/Areas/Admin/Views/Shared/_LayoutPanel.cshtml
@using System.Web.Optimization

<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="stok sayım uygulaması">
    <meta name="author" content="erol akgül">
    <title>@ViewBag.Title</title>
    <link rel="shortcut icon" href="~/logo.ico" />

    <link href="~/Content/sweetalert.css" rel="stylesheet" />

    <!-- CSS -->
    @Styles.Render("~/Areas/Admin/Content/css")
    @Styles.Render("~/bundles/jquery")
    @Styles.Render("~/Content/themes/base/css")

    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    <script src="~/Scripts/Sweet/sweetalert-dev.js"></script>
    <script src="~/Areas/Admin/Scripts/Site.js"></script>

</head>
<body>
    <nav id="main" class="navbar navbar-default" >
        <div class="container-fluid">
            <div class="navbar-header" >
                <div id="item-header">
                    <a class="navbar-brand" href="/Admin/Panel">
                        <img class="img-responsive" src="~/Img/logoP.png" />
                    </a>
                </div>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu1">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="menu1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a id="user" href="#" class="dropdown-toggle" data-toggle="dropdown" style="margin-top:4px;">
                            <span style="font-weight:bold;font-size:16px;font-family:'Myriad Pro';" id="userNamed">
                                @Session["Email"].ToString()
                            </span>  @*HttpContext.Current.User.Identity.Name*@
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu dm_Menu">
                            <li>
                                <a href="~/Admin/Panel/SignOut"><i class="fa fa-fw fa-power-off"></i> Çıkış Yap</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container-fluid">
        <!-- default-->
        <div class="row">
            @RenderBody()
        </div>
    </div>
    @*footer*@
    @*<nav class="navbar navbar-default navbar-fixed-bottom" style="min-height:20px; background-color:#484e55;border-color:#484e55;">
            <div class="container-fluid" style="height:auto" align=center>
                <span class="copyright " style="text-align:center;font-size:13px;">
                    <small style="color:#fff;">© 2016 HAUS Santrifüj Teknolojileri - developer:<a href="http://www.erolakgul.wordpress.com/" target="_blank"> erolakgül</a></small>
                </span>
            </div>
        </nav>*@
</body>
</html>

StockHaus.UI/Areas/Admin/Views/Shared/_LayoutTrace.cshtml
@using System.Web.Optimization

<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewBag.Title</title>
    <link rel="shortcut icon" href="~/logo.ico" />

    <link href="~/Content/PagedList.css" rel="stylesheet" />
    <link href="~/Content/sweetalert.css" rel="stylesheet" />
    <!-- CSS -->
    @Styles.Render("~/Areas/Admin/Content/css")
    @*@Styles.Render("~/bundles/jquery")*@
    @Styles.Render("~/Content/themes/base/css")

    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")

    <script src="~/Areas/Admin/Scripts/Trace_Site.js"></script>
    <script src="~/Scripts/Sweet/sweetalert-dev.js"></script>
</head>
<body>
    <nav id="main" class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu1">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div id="item-header">
                    <a class="navbar-brand" href="/Admin/Trace">
                        <img class="img-responsive" src="~/Img/logoP.png" />
                    </a>
                </div>
            </div>
            <div class="collapse navbar-collapse" id="menu1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a id="user" href="#" class="dropdown-toggle" data-toggle="dropdown" style="margin-top:4px;">
                            <span style="font-weight:bold;font-size:16px;font-family:'Myriad Pro';" id="userNamedTrace">@Session["Email"].ToString()</span>
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu dm_Menu">
                            <li>
                                <a href="~/Admin/Panel/SignOut"><i class="fa fa-fw fa-power-off"></i> Çıkış Yap</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container-fluid">
        <!-- default-->
        <div class="row" style="margin-top:5px;">
            @RenderBody()
        </div>
    </div>
</body>
</html>

StockHaus.UI/Areas/Admin/Views/Shared/_PartialAppRsltShow.cshtml
@using StockHaus.Core.BaseService
@using PagedList
@using PagedList.Mvc
@model IPagedList<StockHaus.ModelClass.AdminPage.InventoriesModel>

<div class="pagedList" style="float:right;">
    @{
        @Html.PagedListPager(Model, id => Url.Action("InventApprovedMat", new { id = id }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "rsltApprovedMat" })) //, OnBegin = "waiting()"
    }
</div>

<table class="table table-hover table-bordered" style="margin-top:20px;">
    <thead style="background-color:rgba(20, 60, 107, 0.84) !important">
        <tr style="color:white;">
            <th>SAYIM KODU</th>
            <th>SAYAN TAKIM</th>
            <th>MALZEME-INDIS</th>
            <th>SERİNO</th>
            <th>Ö. STOK</th>
            <th>İSMİ</th>
            <th>ADET</th>
            <th>DEPO</th>
            <th>S. YERİ</th>
            <th>ONAYLAYAN</th>
            <th>ZAMAN</th>
        </tr>
    </thead>
    <tbody>
        @{
    ServicePoints point = new ServicePoints();

            if (Model != null)
            {
                foreach (var item in Model)
                {
                    int _cT = 0;
                    <tr>
                        <td>@item.InventoryCode</td>

                        @{
                    string _sayanTakım = "";


                    string[] _inList = item.InventoryCode.Split('X');

                    string _countInv = _inList[0];
                    int _team = int.Parse(_inList[1]);
                    int _grp = int.Parse(_inList[2]);

                    var _list = point.InventoryGroupService.TGList(_team, _grp); //db.InventoryGroup.Where(x => x.TeamNo == _team && x.GroupNo == _grp && x.IsActive).ToList();

                    foreach (var itemx in _list)
                    {
                        if (_cT < 2)
                        {

                            if (_sayanTakım == "")
                            {
                                _cT = _cT + 1;
                                _sayanTakım = itemx.PerName;
                            }
                            else
                            {
                                _cT = _cT + 1;
                                _sayanTakım = _sayanTakım + " - " + itemx.PerName;
                            }
                        }
                    }

                        }
                        <td>@_sayanTakım</td>
                        <td>@item.MatCode - @item.MatIndex</td>
                        <td>@item.MatSerialNumber</td>
                        <td>@item.MatSpecialStock</td>
                        <td>@item.MatName</td>
                        <td>@item.MatQuantity</td>
                        <td>@item.MatSection</td>
                        <td>@item.MatSectionPlace</td>
                        <td>@item.ApprovedPers</td>
                        <td>@item.ApprovedDate</td>
                    </tr>
                }
            }
        }
    </tbody>
</table>

StockHaus.UI/Areas/Admin/Views/Shared/_PartialAssignTask.cshtml
@model StockHaus.ModelClass.AdminPage.AssignTasks

@using (Html.BeginForm("AssignTask", "Panel", new { @class = "form-group" }))
{
    @Html.AntiForgeryToken()
    <div class="col-lg-4">
        @Html.Label("Ekip Seç")
        <div id="teamselect2" class="input-group">
            @Html.DropDownListFor(x => x._teamNo, null, htmlAttributes: new { @class = "form-control", @onchange = "FillText()" })
        </div>
        <br />
        @Html.Label("Grup Seç")
        <div id="groupsel2" class="input-group">
            @Html.DropDownListFor(x => x._groupNoL, null, htmlAttributes: new { @class = "form-control", @onchange = "FillText()" })
        </div>
    </div>
    <div id="groupselect" class="col-lg-4">
        @Html.Label("Depo ve Stok Yeri Seç")
        <div id="perNameOne" class="input-group">
            @Html.TextBoxFor(x => x._perName, new { @class = "form-control", @placeholder = "PERSONEL", @type = "text", @readonly = "true" })
        </div>
        <br /><br />
        <div id="perNameTwo" class="input-group">
            @Html.TextBoxFor(x => x._perName2, new { @class = "form-control", @placeholder = "PERSONEL", @type = "text", @readonly = "true" })
        </div><br />
        @Html.Label("Depo")
        <div id="stockStoreSelect" class="input-group">
            @Html.DropDownListFor(x => x._stockStore, null, htmlAttributes: new { @class = "form-control", @onchange = "FillStockPlace()" })
        </div>
        <br />
        <div class="col-lg-6">
            @Html.Label("Stok Yeri (- den)")
            <div id="stockPlaceSelect" class="input-group">
                @Html.DropDownListFor(x => x._stockPlace, null, htmlAttributes: new { @class = "form-control", @onchange = "matchMatSection()" })
            </div>
        </div>
        <div class="col-lg-6">
            @Html.Label("Stok Yeri (- e kadar)")
            <div id="stockPlaceEndSelect" class="input-group">
                @Html.DropDownListFor(x => x._endStockPlace, null, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="input-group">
            <input id="btnLogin" type="submit" name="btnLogin" value="ATA" class="btn btn-block" />
        </div>
        <span id="assignResult" style="display:none;">@ViewBag.Atama</span>
    </div>
}

@* Ekipteki takımların görevli olduğu diğer depo / stok yerleri *@
<div class="col-lg-3 col-lg-offset-1">
    <div class="text-center"> @Html.Label("Ekibin Görevli Olduğu Diğer Yerler")</div>
    <table class="table table-responsive table-bordered">
        <thead><tr style="background-color: rgba(0,0,0,0.5)"><th>Depo</th><th>Stok Yeri(S)</th><th>Stok Yeri(F)</th></tr></thead>
        <tbody id="missionPlace">
            
        </tbody>
    </table>
    <span id="userNamedMission" style="display:none;"></span>
</div>

StockHaus.UI/Areas/Admin/Views/Shared/_PartialChooseWarehouse.cshtml
@model StockHaus.ModelClass.AdminPage.WareStock

@using (@Ajax.BeginForm("GetListMaterial", "Trace", new AjaxOptions { UpdateTargetId = "fillMaterials", InsertionMode = InsertionMode.Replace }))
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-lg-3">
            @Html.Label("Depo")
            <div id="stockStoreSelect" class="input-group">
                @Html.DropDownListFor(x => x._ware, null, htmlAttributes: new { @class = "form-control", @onchange = "FillStockPlace()" })
            </div>
        </div>
        <div class="col-lg-2">
            @Html.Label("Stok Yeri ('den)")
            <div id="stockPlaceSelect" class="input-group">
                @Html.DropDownListFor(x => x._stock, null, htmlAttributes: new { @class = "form-control", @onchange = "MatchStockPlace()" })
            </div>
        </div>
        <div class="col-lg-2">
            @Html.Label("Stok Yeri ('e kadar)")
            <div id="stockEndPlaceSelect" class="input-group">
                @Html.DropDownListFor(x => x._endStockPlace, null, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>
        <div class="col-lg-4">
            <div class="input-group">
                <input id="btnLogin" type="submit" name="btnGetValues" value="GETİR" class="btn btn-block" /> @*onclick="getMaterials()"*@
            </div>
        </div>
    </div>

}

<div id="fillMaterials">
    @* dönen _PartialListMaterial partial view ü ajax ın success inde buraya gömülür.*@
</div>

StockHaus.UI/Areas/Admin/Views/Shared/_PartialCompletePercent.cshtml
@model IList<StockHaus.ModelClass.AdminPage.ShowPercent>

@{
    int count = 0;
    double values = 0;
    double valuesApproved = 0;

    foreach (var item in Model)
    {
        count = count + 1;
        values = item.InventPercent * 100;

        if (values <= 1)
        {
            values = 1;
        }


        valuesApproved = item.ApprovedPercent * 100;

        if (valuesApproved <= 1)
        {
            valuesApproved = 1;
        }

        <tr>
            <td>@count</td>
            <td>@item.WareHouse</td>
            <td>@item.StockPlace</td>
            <td>
                <div id="myProgress_@count">
                    <div id="myBar_@count">
                        0%
                    </div>
                </div>
                <span id="valuePercent_@count" style="display:none">@values</span>
            </td>
            <td>
                <div id="myProgress2_@count">
                    <div id="myBar2_@count">
                        0%
                    </div>
                </div>
                <span id="valuePercent2_@count" style="display:none">@valuesApproved</span>
            </td>
        </tr>
        <script>
    $(document).ready(function () {
        move();
        move2();
    });
    function move() {
        var elem = document.getElementById("myBar_" + @count);
        var value2 = $("#valuePercent_" + @count).text();
        var value = Math.round(parseInt(value2));

        var width = 1;
        var id = setInterval(frame, 80);
        function frame() {
            if (width >= value) {
                clearInterval(id);
            } else {
                width++;
                if (width <= 100) {
                    elem.style.width = width + '%';
                    elem.innerHTML = width * 1 + '%';
                }

            }
        }
    };
    function move2() {
        var elem = document.getElementById("myBar2_" + @count);
        var value = $("#valuePercent2_" + @count).text();
        var value2 = Math.round(parseInt(value));

        var width = 1;
        var id = setInterval(frame, 80);
        function frame() {
            if (width >= value2) {
                clearInterval(id);
            } else {
                width++;
                if (width <= 100) {
                    elem.style.width = width + '%';
                    elem.innerHTML = width * 1 + '%';
                }
            }
        }
    };
        </script>
        <style>
        #myProgress_@count{
            width: 100%;
            background-color: #ddd;
        }

        #myBar_@count {
            width: 5%;
            height: 30px;
            background-color: rgba(255, 0, 0, 0.80); /*#4CAF50   rgba(34, 224, 108, 0.80)*/
            text-align: center;
            line-height: 30px;
            color: white;
        }

        #myProgress2_@count {
            width: 100%;
            background-color: #ddd;
        }

        #myBar2_@count {
            width: 5%;
            height: 30px;
            background-color: rgba(20, 20, 255, 0.85); /*#4CAF50  rgba(224, 248, 10, 0.96)*/
            text-align: center;
            line-height: 30px;
            color: white;
        }
        </style>
    }


}